/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 6/2/2020
 ***********************************************************************************************/

#ifndef DIGITALTWIN_SERIALIZER
#define DIGITALTWIN_SERIALIZER

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "azure_c_shared_utility/xlogging.h"
#include "parson.h"

#include "../SensorTileBox_pnp_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

bool DeviceInformation_SerializeManufacturerProperty(char * payloadBuffer, int size);

bool DeviceInformation_SerializeModelProperty(char * payloadBuffer, int size);

bool DeviceInformation_SerializeSwVersionProperty(char * payloadBuffer, int size);

bool DeviceInformation_SerializeOsNameProperty(char * payloadBuffer, int size);

bool DeviceInformation_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size);

bool DeviceInformation_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size);

bool DeviceInformation_SerializeTotalStorageProperty(char * payloadBuffer, int size);

bool DeviceInformation_SerializeTotalMemoryProperty(char * payloadBuffer, int size);

bool SensorTile_Box_SerializeTemperatureTelemetry(char * payloadBuffer, int size);

bool SensorTile_Box_SerializePressureTelemetry(char * payloadBuffer, int size);

bool SensorTile_Box_SerializeHumidityTelemetry(char * payloadBuffer, int size);

bool SensorTile_Box_SerializeAcceleroTelemetry(char * payloadBuffer, int size);

bool SensorTile_Box_SerializeGyroTelemetry(char * payloadBuffer, int size);

bool SensorTile_Box_SerializeMegnetoTelemetry(char * payloadBuffer, int size);

#ifdef __cplusplus
}
#endif

#endif // DIGITALTWIN_SERIALIZER
