/*******************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.8.
 *
 * You need to add your implementation here to:
 *    - get telemetry data from device/sensor
 *    - set read-only property data
 *    - handle read-write property callback
 *    - process device command
 *
 * Generated Date: 6/2/2020
 *******************************************************************************************/

#include "SensorTileBox_pnp_impl.h"
#include "utilities/digitaltwin_serializer.h"
#include "utilities/deviceinformation_interface.h"
#include "utilities/sensortile_box_interface.h"
#include "DeviceInformation.h"
#include "SensorTileBox.h"

#ifdef _WIN32
#include <windows.h>
#endif

#define Payload_Buffer_Size 256

static char szProperty[256];

void SendTelemetry_Succeeded_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on success.

    LogInfo("DigitalTwin successfully delivered telemetry message for component %s", interfaceName);
}

void SendTelemetry_Error_Callback(const char* interfaceName)
{
    // If needed, put your business logic here to handle the confirmation of the delivery for device telemetry on failure.

    LogInfo("DigitalTwin failed to deliver telemetry message for %s", interfaceName);
}

void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback reporting property on success.

    LogInfo("DigitalTwin successfully report writable property for %s::%s", interfaceName, propertyName);
}

void ReportProperty_Error_Callback(const char* interfaceName, const char* propertyName)
{
    // If needed, put your business logic here to handle the result callback of reporting property on failure.

    LogInfo("DigitalTwin failed to report writable property for %s::%s", interfaceName, propertyName);
}

char* DeviceInformation_Property_GetManufacturer()
{
    snprintf(szProperty, sizeof(szProperty), "%s", "Unknown");

    if (GetManufacturer(szProperty, sizeof(szProperty)))
    {
        printf("GetManufacturer()          : %s\r\n", szProperty);
    }
    return szProperty;
}

char* DeviceInformation_Property_GetModel()
{
    snprintf(szProperty, sizeof(szProperty), "%s", "Unknown");

    if (GetModel(szProperty, sizeof(szProperty)))
    {
        printf("GetModel()                 : %s\r\n", szProperty);
    }
    return szProperty;
}

char* DeviceInformation_Property_GetSwVersion()
{
    snprintf(szProperty, sizeof(szProperty), "%s", "Unknown");

    if (GetSwVersion(szProperty, sizeof(szProperty)))
    {
        printf("GetSwVersion()             : %s\r\n", szProperty);
    }
    return szProperty;
}

char* DeviceInformation_Property_GetOsName()
{
    snprintf(szProperty, sizeof(szProperty), "%s", "Unknown");

    if (GetOsName(szProperty, sizeof(szProperty))) {
        printf("GetOsName()                : %s\r\n", szProperty);
    }
    return szProperty;
}

char* DeviceInformation_Property_GetProcessorArchitecture()
{
    snprintf(szProperty, sizeof(szProperty), "%s", "Unknown");

    if (GetProcessorArchitecture(szProperty, sizeof(szProperty))) {
        printf("GetProcessorArchitecture() : %s\r\n", szProperty);
    }
    return szProperty;
}

char* DeviceInformation_Property_GetProcessorManufacturer()
{
    snprintf(szProperty, sizeof(szProperty), "%s", "Unknown");

    if (GetProcessorManufacturer(szProperty, sizeof(szProperty))) {
        printf("GetProcessorManufacturer() : %s\r\n", szProperty);
    }
    return szProperty;
}

long DeviceInformation_Property_GetTotalStorage()
{
    long diskSize = GetTotalStorage();
    printf("Storage                    : %lu (%lu GB)\r\n", diskSize, (diskSize / 1024/1024));
    return diskSize;
}

long DeviceInformation_Property_GetTotalMemory()
{
    ULONG64 memSize = GetTotalMemory();
    printf("Memory                     : %lu\r\n", memSize);
    return (long)(memSize);
}

float SensorTile_Box_Telemetry_ReadTemperature()
{
    return GetTemperature();
}

float SensorTile_Box_Telemetry_ReadPressure()
{
    return GetPressure();
}

float SensorTile_Box_Telemetry_ReadHumidity()
{
    return GetHumidity();
}

void SensorTile_Box_Telemetry_ReadAccelero(SensorTile_Box_ACCELERO * accelerometer)
{
    THREE_AXIS_DATA data;

    GetAccelerometer(&data);

    accelerometer->X = data.X;
    accelerometer->Y = data.Y;
    accelerometer->Z = data.Z;
}

void SensorTile_Box_Telemetry_ReadGyro(SensorTile_Box_GYRO * gyrometer)
{
    THREE_AXIS_DATA data;

    GetGyrometer(&data);

    gyrometer->X = data.X;
    gyrometer->Y = data.Y;
    gyrometer->Z = data.Z;
}

void SensorTile_Box_Telemetry_ReadMegneto(SensorTile_Box_MEGNETO * megnetometer)
{
    THREE_AXIS_DATA data;

    GetMagnetometer(&data);

    megnetometer->X = data.X;
    megnetometer->Y = data.Y;
    megnetometer->Z = data.Z;
}

